#! /bin/sh

[ -f /usr/sbin/udhcpd ] || exit 0

start() {
	printf "Starting udhcpd: "
	udhcpd -S /etc/udhcpd.conf
	echo "done"
}


stop() {
	printf "Stopping udhcpd: "
	killall udhcpd
	echo "done"
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
