#!/bin/sh
case "$1" in
  start)
    /usr/bin/respawn_retroarch.sh &
    ;;
  stop)
    for KILLPID in `ps | grep 'retroarch' | awk ' { print $1;}'`; do
      kill -9 $KILLPID;
    done
    exit 1
    ;;
  *)
    exit 1
    ;;
esac

exit 0
